version: '3.8'

volumes:
  mysql-data:
networks:
  spring-boot-mysql-network:
    name: spring-boot-mysql-network
services:
  mysqldb:
    image: mysql:lts
    command: --mysql-native-password=ON
    ports:
      - "3308:3306"
    environment:
      - MYSQL_DATABASE=techstore
      - MYSQL_USER=techstore_user
      - MYSQL_PASSWORD=1234567890=
      - MYSQL_ROOT_PASSWORD=0123456789=
    networks:
      - spring-boot-mysql-network
    volumes:
      - mysql-data=/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      retries: 5
      interval: 3s
      timeout: 30s
  techstore:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      mysqldb:
        condition: service_healthy
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - SPRING_DATASOURCE_URL=jdbc://mysqldb:3306/techstore
      - SPRING_DATASOURCE_USERNAME=techstore_user
      - SPRING_DATASOURCE_PASSWORD=1234567890=
    networks:
      - spring-boot-mysql-network



